version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: streamlit_container
    ports:
      - "8501:8501"
    volumes:
      # Change the left side to a real path on your Portainer server
      - /home/support/streamlit_apps:/app/pages
    restart: always
